version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    volumes:
      - static_volume:/usr/src/app/app/static
      - media_volume:/usr/src/app/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.app
    depends_on:
      - database
    restart: always

  database:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.database
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/app/static
      - media_volume:/usr/src/app/app/media
    ports:
      - 80:80
    depends_on:
      - app
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
