# Generated by Django 4.2.4 on 2023-08-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0002_category_alter_image_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="categories",
            field=models.ManyToManyField(to="album.category"),
        ),
    ]
