# Generated by Django 4.2.4 on 2023-08-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0003_image_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("tel", models.CharField(max_length=100)),
            ],
        ),
    ]
