# Generated by Django 4.2.4 on 2023-08-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("photo", models.ImageField(upload_to="profilephoto/")),
            ],
        ),
    ]
