# Generated by Django 4.2.4 on 2023-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0006_category_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="link",
            field=models.SlugField(),
        ),
    ]
